# Generated by Django 5.2.12 on 2026-04-09 11:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0002_subjects_grades'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grades',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_app.subjects'),
        ),
    ]
