# Generated by Django 5.2.12 on 2026-04-09 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0003_alter_grades_subject'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grades',
            name='lesso_topic',
        ),
    ]
