# Generated by Django 5.2.12 on 2026-04-09 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0004_remove_grades_lesso_topic'),
    ]

    operations = [
        migrations.AddField(
            model_name='grades',
            name='lesson_topic',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
