# Generated by Django 5.2.12 on 2026-04-11 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0007_attendance_delete_attendace'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Attendance',
        ),
    ]
