# Generated by Django 5.2.12 on 2026-04-11 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0009_attendance'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendance',
            old_name='is_present',
            new_name='attendance',
        ),
    ]
