# Generated by Django 5.2.12 on 2026-04-16 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0013_alter_payment_paid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='date_pay',
            field=models.DateField(blank=True),
        ),
    ]
