# Generated by Django 5.2.12 on 2026-04-16 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0014_alter_payment_date_pay'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='date_pay',
            field=models.DateField(blank=True, null=True),
        ),
    ]
