# Generated by Django 5.2.12 on 2026-04-18 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0016_users_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='avatar',
            field=models.ImageField(default='media/default.jpeg', upload_to='media/avatars/'),
        ),
    ]
